// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cooperatives.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCooperative = `-- name: GetCooperative :one
SELECT id, name, legal_number, address, created_at FROM cooperatives
WHERE id = $1
`

func (q *Queries) GetCooperative(ctx context.Context, id pgtype.UUID) (Cooperative, error) {
	row := q.db.QueryRow(ctx, getCooperative, id)
	var i Cooperative
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LegalNumber,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}
