// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Cooperative struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	LegalNumber pgtype.Text        `json:"legal_number"`
	Address     pgtype.Text        `json:"address"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Deduction struct {
	ID              pgtype.UUID        `json:"id"`
	MemberID        pgtype.UUID        `json:"member_id"`
	Type            string             `json:"type"`
	PrincipalAmount pgtype.Numeric     `json:"principal_amount"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DeductionTransaction struct {
	ID              pgtype.UUID        `json:"id"`
	DeductionID     pgtype.UUID        `json:"deduction_id"`
	PayoutRunItemID pgtype.UUID        `json:"payout_run_item_id"`
	AmountApplied   pgtype.Numeric     `json:"amount_applied"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
}

type HarvestRecord struct {
	ID              pgtype.UUID        `json:"id"`
	MemberID        pgtype.UUID        `json:"member_id"`
	CooperativeID   pgtype.UUID        `json:"cooperative_id"`
	HarvestDate     pgtype.Date        `json:"harvest_date"`
	TbsWeightKg     pgtype.Numeric     `json:"tbs_weight_kg"`
	QualityGrade    string             `json:"quality_grade"`
	GpsLat          pgtype.Float8      `json:"gps_lat"`
	GpsLng          pgtype.Float8      `json:"gps_lng"`
	PhotoUrl        pgtype.Text        `json:"photo_url"`
	DeviceID        pgtype.Text        `json:"device_id"`
	ClientCreatedAt pgtype.Timestamptz `json:"client_created_at"`
	Status          string             `json:"status"`
	ValidatedBy     pgtype.UUID        `json:"validated_by"`
	ValidatedAt     pgtype.Timestamptz `json:"validated_at"`
	PriceID         pgtype.UUID        `json:"price_id"`
	PayoutRunItemID pgtype.UUID        `json:"payout_run_item_id"`
	CorrectsID      pgtype.UUID        `json:"corrects_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Member struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	CooperativeID pgtype.UUID        `json:"cooperative_id"`
	MemberNumber  string             `json:"member_number"`
	Nik           pgtype.Text        `json:"nik"`
	FullName      string             `json:"full_name"`
	Address       pgtype.Text        `json:"address"`
	LandAreaHa    pgtype.Numeric     `json:"land_area_ha"`
	BankName      pgtype.Text        `json:"bank_name"`
	BankAccountNo pgtype.Text        `json:"bank_account_no"`
	JoinDate      pgtype.Date        `json:"join_date"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Type              string             `json:"type"`
	Title             string             `json:"title"`
	Body              pgtype.Text        `json:"body"`
	RelatedEntityType pgtype.Text        `json:"related_entity_type"`
	RelatedEntityID   pgtype.UUID        `json:"related_entity_id"`
	ReadAt            pgtype.Timestamptz `json:"read_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PayoutRun struct {
	ID            pgtype.UUID        `json:"id"`
	CooperativeID pgtype.UUID        `json:"cooperative_id"`
	PeriodStart   pgtype.Date        `json:"period_start"`
	PeriodEnd     pgtype.Date        `json:"period_end"`
	Status        string             `json:"status"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	ApprovedBy    pgtype.UUID        `json:"approved_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PayoutRunItem struct {
	ID              pgtype.UUID    `json:"id"`
	PayoutRunID     pgtype.UUID    `json:"payout_run_id"`
	MemberID        pgtype.UUID    `json:"member_id"`
	GrossAmount     pgtype.Numeric `json:"gross_amount"`
	DeductionsTotal pgtype.Numeric `json:"deductions_total"`
	NetAmount       pgtype.Numeric `json:"net_amount"`
	Status          string         `json:"status"`
}

type PriceReference struct {
	ID            pgtype.UUID        `json:"id"`
	CooperativeID pgtype.UUID        `json:"cooperative_id"`
	Grade         string             `json:"grade"`
	PricePerKg    pgtype.Numeric     `json:"price_per_kg"`
	EffectiveDate pgtype.Date        `json:"effective_date"`
	SetBy         pgtype.UUID        `json:"set_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SyncBatch struct {
	ID          pgtype.UUID        `json:"id"`
	MemberID    pgtype.UUID        `json:"member_id"`
	DeviceID    pgtype.Text        `json:"device_id"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	RecordCount int32              `json:"record_count"`
	Status      string             `json:"status"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	CooperativeID pgtype.UUID        `json:"cooperative_id"`
	Email         pgtype.Text        `json:"email"`
	Phone         pgtype.Text        `json:"phone"`
	PasswordHash  string             `json:"password_hash"`
	Role          string             `json:"role"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
